# CMake generated Testfile for 
# Source directory: /home/overmind/.openclaw/workspace/max-compression/tests
# Build directory: /home/overmind/.openclaw/workspace/max-compression/build_dbg/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(roundtrip "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/test_roundtrip")
set_tests_properties(roundtrip PROPERTIES  _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;9;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(bwt_levels "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/test_bwt_levels")
set_tests_properties(bwt_levels PROPERTIES  _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;17;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(lzrc_roundtrip "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/test_lzrc")
set_tests_properties(lzrc_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;28;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(comprehensive "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/test_comprehensive")
set_tests_properties(comprehensive PROPERTIES  _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;36;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(rle2 "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/test_rle2")
set_tests_properties(rle2 PROPERTIES  _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;44;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(fse "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/test_fse")
set_tests_properties(fse PROPERTIES  _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;51;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(fse_mini "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/test_fse_mini")
set_tests_properties(fse_mini PROPERTIES  _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;58;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(fuzz_roundtrip "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/test_fuzz_roundtrip" "1000" "8192")
set_tests_properties(fuzz_roundtrip PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;66;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(malformed "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/test_malformed")
set_tests_properties(malformed PROPERTIES  _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;75;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(edge_cases "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/test_edge_cases")
set_tests_properties(edge_cases PROPERTIES  _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;83;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(stress "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/test_stress")
set_tests_properties(stress PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;91;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(fuzz_lzrc "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/fuzz_lzrc" "200" "16384")
set_tests_properties(fuzz_lzrc PROPERTIES  TIMEOUT "300" _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;100;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(regression "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/test_regression")
set_tests_properties(regression PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;111;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(streaming_decompress "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/test_streaming_decompress")
set_tests_properties(streaming_decompress PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;120;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(multifile_roundtrip "/home/overmind/.openclaw/workspace/max-compression/tests/test_multifile.sh" "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/mcx")
set_tests_properties(multifile_roundtrip PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;126;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(cli_flags_pipe "/home/overmind/.openclaw/workspace/max-compression/tests/test_cli_flags.sh" "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/mcx")
set_tests_properties(cli_flags_pipe PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;130;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(silesia_roundtrip "/home/overmind/.openclaw/workspace/max-compression/tests/test_silesia_roundtrip.sh" "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/mcx")
set_tests_properties(silesia_roundtrip PROPERTIES  TIMEOUT "600" _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;134;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(split_roundtrip "/home/overmind/.openclaw/workspace/max-compression/tests/test_split.sh" "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/mcx")
set_tests_properties(split_roundtrip PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;138;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(preserve_mtime "/home/overmind/.openclaw/workspace/max-compression/tests/test_preserve_mtime.sh" "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/mcx")
set_tests_properties(preserve_mtime PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;142;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(bench_flags "/home/overmind/.openclaw/workspace/max-compression/tests/test_bench_flags.sh" "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/mcx")
set_tests_properties(bench_flags PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;146;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
add_test(decompress_check "/home/overmind/.openclaw/workspace/max-compression/tests/test_decompress_check.sh" "/home/overmind/.openclaw/workspace/max-compression/build_dbg/bin/mcx")
set_tests_properties(decompress_check PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;150;add_test;/home/overmind/.openclaw/workspace/max-compression/tests/CMakeLists.txt;0;")
